p1: p1.c
	gcc -o p1.o p1.c
	./p1.o

p2: p2.c
	gcc -o p2.o p2.c
	./p2.o

p3: p3.c
	gcc -o p3.o p3.c
	./p3.o

p4: p4.c
	gcc -o p4.o p4.c
	./p4.o

p5: p5.c
	gcc -o p5.o p5.c
	./p5.o

.PHONY: clean

clean:
	rm -f *.o
	rm -f *.txt